### ISSUE TITLE
Dont times * 100 on amount

### ISSUE THREAD

**Issue by simplenotezy** [tuurbo/spreedly#20]
You should not be doing times on the amount. Because the currency cannot always be split into 100.

For example YPN (japanese) will not be multiplied with 100.

**Comment by tuurbo** [comment]
Thanks for the heads up. I'll look into it

**Comment by simplenotezy** [comment]
Any updates @tuurbo ? :)

**Comment by tuurbo** [comment]
I'll try to work on it this weekend :D

**Comment by simplenotezy** [comment]
Nice! Them I can push monday

**Comment by adridev** [comment]
Hey guys, take a look to http://verraes.net/2011/04/fowler-money-pattern-in-php/ and its implementation in PHP https://github.com/moneyphp/money

**Comment by tuurbo** [comment]
released a beta version of 2.0 (don't use in production), needs more testing.
- no longer convert money to cents
- psr2
- switched internal api calls from xml to json

https://github.com/tuurbo/spreedly/tree/2.0

**Comment by simplenotezy** [comment]
Looks good. When can we use in production? Is there anything you would like me to test?

**Comment by tuurbo** [comment]
@canfiax I've now tested quite a few methods, just didn't want to push a major release until i'm sure there aren't any major issues. You can try it out with `composer require tuurbo/spreedly:2.0.x-dev`. I'll try to push to master within the next couple days

**Comment by tuurbo** [comment]
Plan on releasing 2.0 tonight.

**Comment by simplenotezy** [comment]
Awesome!! Good job 💪🏽
