### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by simplenotezy** [tuurbo/spreedly#21]
What is the max allowed timeout in the setup?

According to Spreedly we need to set it to 64 seconds to be safe. https://docs.spreedly.com/reference/api/old/timeouts/

**Comment by tuurbo** [comment]
You can override the default timeouts in the config.

```
$config = [
    'key' => '', // Environment key
    'secret' => '', // Signing Secret
    'gateway' => '', // Default gateway
    'timeout' => 123, // Default 15
    'connect_timeout' => 456 // Default 10
];
```

http://docs.guzzlephp.org/en/latest/request-options.html#timeout
http://docs.guzzlephp.org/en/latest/request-options.html#connect-timeout

**Comment by simplenotezy** [comment]
So the timeout Spreedly is talking about, is that timeout, or connect_timeout?

And shouldn't the default be 64 as recommended by Spreedly?

**Comment by tuurbo** [comment]
I believe connect_timeout is the time it takes to connect to Spreedly and timeout is the time it takes after the connection is made to Spreedly. So the 64 seconds Spreedly was referring to would be timeout. I have no plans to change the default, but I'm considering adding a timeout method that could be used override the timeout for specific api calls, `Spreedly::timeout(64)->payment('sfds3gh41287dhfui')->purchase(1098)`

**Comment by simplenotezy** [comment]
I am curious. Why not just add the recommended timeout settings to provide a stable experience?

They recommend having it to 64 secs as per their docs.

**Comment by tuurbo** [comment]
After thinking about it more, you right. So i set the default to 64 seconds and added a new method to override api calls like `Spreedly::timeout(15)->payment('sfds3gh41287dhfui')->get()` that don't need 64 seconds.

https://github.com/tuurbo/spreedly#changelog

**Comment by lasergoat** [comment]
How do you know which calls need 15 and which need 64? Is it calls that reach to a gateway that need the 64?

**Comment by tuurbo** [comment]
@lasergoat Going from memory, up to 15 secs to connect to spreedly and up to 64 secs for spreedly to connect to the gateway.

**Comment by tuurbo** [comment]
@lasergoat https://docs.spreedly.com/guides/debugging/#timeouts
