### ISSUE TITLE
Issue with required version of Guzzle (4.0)

### ISSUE THREAD

**Issue by lasergoat** [tuurbo/spreedly#3]
I'm excited to use this library. However when doing `composer update` I get this error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tuurbo/spreedly 0.9.2 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - tuurbo/spreedly 0.9.1 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - tuurbo/spreedly 0.9.0 requires guzzlehttp/guzzle ~4.0 -> no matching package found.
    - Installation request for tuurbo/spreedly ~0.9 -> satisfiable by tuurbo/spreedly[0.9.0, 0.9.1, 0.9.2].

```

Before finding this library I was hitting spreedly with guzzle directly, and using Guzzle 5.2. Is there a way I can overwrite your requirement of an old version of Guzzle? Or, is that even the problem.

**Comment by tuurbo** [comment]
I'm no composer expert but 4.0 just worked for me. I went ahead and updated it to 5.2 since 4 was EOL.

**Comment by lasergoat** [comment]
Alright, thanks!
