### ISSUE TITLE
Failed requests don't always throw exception

### ISSUE THREAD

**Issue by adam1010** [tuurbo/spreedly#33]
In the Client::request() method you are checking for certain error codes and throwing exceptions when they occur, but if it's not one you check for, you just set `$this->status = 'error'`  so that user's of the library must check for this variable every single time we make a request.

Code: https://github.com/tuurbo/spreedly/blob/master/src/Client.php#L82

Are you opposed to always throwing an exception on line 82?  If you are, would you be opposed to adding a configuration variable we could set to throw exceptions (that's disabled by default)?  I can write the code if you like.

We've seen Spreedly APIs returning `HTTP 504` and other error response codes that aren't currently throwing an exception so our code just keeps chugging along.

**Comment by tuurbo** [comment]
My company just decided to stop using Spreedly and we plan to archive this repo since we will no longer be able to test it in production. I recommend forking the repo or using ```$resp->fails()``` to catch the error. Sorry
