### ISSUE TITLE
Response wrapper methods throw exceptions inappropriately

### ISSUE THREAD

**Issue by joshua-paddle** [tuurbo/spreedly#7]
In Client model.

For instance, if $this->response['payment_method'] is not set, then paymentToken() throws an exception, but response('payment_method.token') correctly returns null.

Is this expected behaviour? Should paymentToken not be wrapping a call to response(), rather than accessing the attribute directly?

**Comment by tuurbo** [comment]
Your right. Changes are up. Thanks
