### ISSUE TITLE
credit expects cents not dollars.cents

### ISSUE THREAD

**Issue by lasergoat** [tuurbo/spreedly#9]
For the new general credit method, the error is this:

`Amount should be specified as an integer value corresponding to the number of cents. Example: $42.34 is 4234 cents.`

I assume that the other methods are doing this for me, but not general_credit

**Comment by tuurbo** [comment]
Whoops, sorry about that. I'll be able to fix it once I'm near a computer in about an hour

**Comment by lasergoat** [comment]
yeah, the fix is line 154 of Payment.php 

```
                'amount' => $amount * 100,
```

plus your spec test.

**Comment by tuurbo** [comment]
Fixed!
